modLoader = "lowcodefml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Nova-Committee/Gunners/issues/"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
displayTest = "IGNORE_SERVER_VERSION"
[[dependencies.${ mod_id }]]
modId = "cgm"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
